# Generated by Django 3.1.3 on 2020-11-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('es_lente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='historialMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('historial_medico', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='polo_app.historialmedico')),
                ('medico', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Paciente_medico', to='polo_app.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('medico', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='medico_turno', to='polo_app.medico')),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_turno', to='polo_app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_producto', to='polo_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('medio_de_pago', models.CharField(max_length=20)),
                ('nombre_paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_paciente', to='polo_app.paciente')),
                ('nombre_producto', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='producto_pedido', to='polo_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='pedido',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_paciente', to='polo_app.pedido'),
        ),
        migrations.AddField(
            model_name='medico',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Medico_paciente', to='polo_app.paciente'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='medico',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='medico_historial', to='polo_app.medico'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='nombre_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polo_app.paciente'),
        ),
    ]
