# Generated by Django 3.1.3 on 2020-11-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='historial_medico',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='medico_historial', to='polo_app.historialmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='polo_app.historialmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pedido',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_paciente', to='polo_app.pedido'),
        ),
    ]
