# Generated by Django 3.1.3 on 2020-11-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0002_auto_20201120_0043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='medico',
            new_name='medico_id',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='nombre_paciente',
            new_name='paciente_id',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='paciente',
            new_name='paciente_id',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='historial_medico',
            new_name='historial_medico_id',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='medico',
            new_name='medico_id',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='pedido',
            new_name='pedido_id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='entregado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_paciente',
            new_name='paciente_id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_producto',
            new_name='producto_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='medico',
            new_name='medico_id',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='paciente',
            new_name='paciente_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='medico',
            name='historial_medico_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='polo_app.historialmedico'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(max_length=200, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='observaciones',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='medio_de_pago',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polo_app.pedido')),
            ],
        ),
    ]
