# Generated by Django 3.1.3 on 2020-11-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0003_auto_20201120_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmedico',
            old_name='medico_id',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='historialmedico',
            old_name='paciente_id',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='historial_medico_id',
            new_name='historial_medico',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='medico_id',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='paciente_id',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='taller',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='medico_id',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='paciente_id',
            new_name='paciente',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='historial_medico_id',
        ),
        migrations.AddField(
            model_name='medico',
            name='historial_medico',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='medico_historial', to='polo_app.historialmedico'),
        ),
    ]
