# Generated by Django 3.1.3 on 2020-11-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0004_auto_20201120_2130'),
        ('polo_app', '0003_auto_20201121_1956'),
    ]

    operations = [
    ]
