# Generated by Django 3.1.3 on 2020-11-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0005_merge_20201122_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='paciente_id',
        ),
        migrations.AddField(
            model_name='medico',
            name='paciente',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_medico', to='polo_app.paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='historial_medico',
            field=models.ForeignKey(blank='true', default=3, null='true', on_delete=django.db.models.deletion.CASCADE, related_name='medico_historial', to='polo_app.historialmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.ForeignKey(blank='true', default=2, null='true', on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='polo_app.historialmedico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(blank='true', default=2, null='true', on_delete=django.db.models.deletion.CASCADE, related_name='Paciente_medico', to='polo_app.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pedido',
            field=models.ForeignKey(blank='true', default=3, null='true', on_delete=django.db.models.deletion.CASCADE, related_name='pedido_paciente', to='polo_app.pedido'),
        ),
    ]
