# Generated by Django 3.1.3 on 2020-11-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0006_auto_20201122_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polo_app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polo_app.paciente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polo_app.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polo_app.producto')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polo_app.ventas')),
            ],
        ),
    ]
