# Generated by Django 3.1.3 on 2020-11-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0007_gerencia_ventas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
