# Generated by Django 3.1.3 on 2020-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polo_app', '0008_auto_20201122_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(default=1, upload_to='img/'),
        ),
    ]
